[phases.setup]
nixPkgs = ["nodejs_22", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile --ignore-engines"]

[phases.build]
cmds = ["yarn run build"]

[start]
cmd = "yarn run start"

[variables]
NODE_ENV = "production"
PORT = "3000"
